name = "proof-of-tests"
main = "build/worker/shim.mjs"
compatibility_date = "2024-09-19"

routes = [
    { pattern = "proof-of-tests.org", zone_name = "proof-of-tests.org", custom_domain = true },
]


[assets]
directory = "assets"

[build]
command = """
mkdir -p assets/pkg &&
cp public/* assets/ &&
npx tailwindcss --minify -i style/tailwind.css -o assets/style.css &&
wasm-pack build --out-dir assets/pkg --no-typescript --release --target web --out-name client --features hydrate --no-default-features &&
worker-build --release --features ssr --no-default-features
"""

[env.quick.build]
command = """
mkdir -p assets/pkg &&
cp public/* assets/ &&
npx tailwindcss --minify -i style/tailwind.css -o assets/style.css &&
wasm-pack build --out-dir assets/pkg --no-typescript --no-opt --target web --out-name client --features hydrate --no-default-features &&
worker-build --no-opt --features ssr --no-default-features
"""
